
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trading_company_development

test:
  <<: *default
  database: trading_company_test

production:
  <<: *default
  database: trading_company_production
  username: trading_company
  password: <%= ENV['APPNAME_DATABASE_PASSWORD'] %>
